### ISSUE TITLE
Is it possible for the dockerized multi-cron to run jobs on other containers?

### ISSUE THREAD

**Issue by hiphamster** [junkiebev/multi-cron#1]
+

**Comment by junkiebev** [comment]
@hiphamster - I’m not sure what you are trying to accomplish, but if you mount the Docker socket, you’d be able to start/stop/read logs from/etc any containers. if you give me more details, I might be able to advise you.

**Comment by hiphamster** [comment]
Thanks for the reply. Here's a sample scenario - a mariadb is running in a container. I'd like to schedule a mysqldump to run periodically. Would it be possible to schedule a job in multi-cron, to have it connect to mariadb container and run mysqldump. In a manner similar to docker exec.

**Comment by junkiebev** [comment]
That’s actually what I wrote it for - job one backs up to Azure blob storage, job 2 deletes all backups older than 30 days 😎

You’d need to connect to the MySQL server to run the command which means you’d need to expose the application port somehow to the multi-cron container. In k8s, this is best accomplished by targeting a service but you can do whatever you’d like.

**Comment by hiphamster** [comment]
Accessing another container via port makes sense, but that's not exactly what i want to do. With mariadb, i'd like to run mysqldump client on the mariadb container. That's what i meant by 'docker exec' manner. If i were to go with your suggested route, it would be more like 'docker run', which means another container would have to be created.

**Comment by junkiebev** [comment]
Docker is designed to run the main process at `PID 1` - in the case of your database instance, that'd by MariaDB and in the case of your Multicron container, that'd be multicron.
